// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: unaryMessage.proto

#include "unaryMessage.pb.h"
#include "unaryMessage.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace message {

static const char* Message_method_names[] = {
  "/message.Message/SendMessage",
};

std::unique_ptr< Message::Stub> Message::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Message::Stub> stub(new Message::Stub(channel, options));
  return stub;
}

Message::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMessage_(Message_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Message::Stub::SendMessage(::grpc::ClientContext* context, const ::message::MessageRequest& request, ::message::MessageReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::MessageRequest, ::message::MessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void Message::Stub::async::SendMessage(::grpc::ClientContext* context, const ::message::MessageRequest* request, ::message::MessageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::MessageRequest, ::message::MessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void Message::Stub::async::SendMessage(::grpc::ClientContext* context, const ::message::MessageRequest* request, ::message::MessageReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::MessageReply>* Message::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::message::MessageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::MessageReply, ::message::MessageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::MessageReply>* Message::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::message::MessageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

Message::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Message_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Message::Service, ::message::MessageRequest, ::message::MessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Message::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::MessageRequest* req,
             ::message::MessageReply* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
}

Message::Service::~Service() {
}

::grpc::Status Message::Service::SendMessage(::grpc::ServerContext* context, const ::message::MessageRequest* request, ::message::MessageReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

