// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ClientStream.proto
#ifndef GRPC_ClientStream_2eproto__INCLUDED
#define GRPC_ClientStream_2eproto__INCLUDED

#include "ClientStream.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace C_Stream {

class ServiceStream final {
 public:
  static constexpr char const* service_full_name() {
    return "C_Stream.ServiceStream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::C_Stream::StreamRequest>> SendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::C_Stream::StreamRequest>>(SendMessageRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::C_Stream::StreamRequest>> AsyncSendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::C_Stream::StreamRequest>>(AsyncSendMessageRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::C_Stream::StreamRequest>> PrepareAsyncSendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::C_Stream::StreamRequest>>(PrepareAsyncSendMessageRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::ClientWriteReactor< ::C_Stream::StreamRequest>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::C_Stream::StreamRequest>* SendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::C_Stream::StreamRequest>* AsyncSendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::C_Stream::StreamRequest>* PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::C_Stream::StreamRequest>> SendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::C_Stream::StreamRequest>>(SendMessageRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::C_Stream::StreamRequest>> AsyncSendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::C_Stream::StreamRequest>>(AsyncSendMessageRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::C_Stream::StreamRequest>> PrepareAsyncSendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::C_Stream::StreamRequest>>(PrepareAsyncSendMessageRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::ClientWriteReactor< ::C_Stream::StreamRequest>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::C_Stream::StreamRequest>* SendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response) override;
    ::grpc::ClientAsyncWriter< ::C_Stream::StreamRequest>* AsyncSendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::C_Stream::StreamRequest>* PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendMessage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendMessage(::grpc::ServerContext* context, ::grpc::ServerReader< ::C_Stream::StreamRequest>* reader, ::C_Stream::StreamReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::C_Stream::StreamRequest>* /*reader*/, ::C_Stream::StreamReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendMessage(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::C_Stream::StreamReply, ::C_Stream::StreamRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendMessage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendMessage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::C_Stream::StreamRequest, ::C_Stream::StreamReply>(
            [this](
                   ::grpc::CallbackServerContext* context, ::C_Stream::StreamReply* response) { return this->SendMessage(context, response); }));
    }
    ~WithCallbackMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::C_Stream::StreamRequest>* /*reader*/, ::C_Stream::StreamReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::C_Stream::StreamRequest>* SendMessage(
      ::grpc::CallbackServerContext* /*context*/, ::C_Stream::StreamReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendMessage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::C_Stream::StreamRequest>* /*reader*/, ::C_Stream::StreamReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::C_Stream::StreamRequest>* /*reader*/, ::C_Stream::StreamReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendMessage(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendMessage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->SendMessage(context, response); }));
    }
    ~WithRawCallbackMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::C_Stream::StreamRequest>* /*reader*/, ::C_Stream::StreamReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* SendMessage(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace C_Stream


#endif  // GRPC_ClientStream_2eproto__INCLUDED
