// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ClientStream.proto

#include "ClientStream.pb.h"
#include "ClientStream.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace C_Stream {

static const char* ServiceStream_method_names[] = {
  "/C_Stream.ServiceStream/SendMessage",
};

std::unique_ptr< ServiceStream::Stub> ServiceStream::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServiceStream::Stub> stub(new ServiceStream::Stub(channel, options));
  return stub;
}

ServiceStream::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMessage_(ServiceStream_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::C_Stream::StreamRequest>* ServiceStream::Stub::SendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response) {
  return ::grpc::internal::ClientWriterFactory< ::C_Stream::StreamRequest>::Create(channel_.get(), rpcmethod_SendMessage_, context, response);
}

void ServiceStream::Stub::async::SendMessage(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::ClientWriteReactor< ::C_Stream::StreamRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::C_Stream::StreamRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::C_Stream::StreamRequest>* ServiceStream::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::C_Stream::StreamRequest>::Create(channel_.get(), cq, rpcmethod_SendMessage_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::C_Stream::StreamRequest>* ServiceStream::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, ::C_Stream::StreamReply* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::C_Stream::StreamRequest>::Create(channel_.get(), cq, rpcmethod_SendMessage_, context, response, false, nullptr);
}

ServiceStream::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServiceStream_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< ServiceStream::Service, ::C_Stream::StreamRequest, ::C_Stream::StreamReply>(
          [](ServiceStream::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::C_Stream::StreamRequest>* reader,
             ::C_Stream::StreamReply* resp) {
               return service->SendMessage(ctx, reader, resp);
             }, this)));
}

ServiceStream::Service::~Service() {
}

::grpc::Status ServiceStream::Service::SendMessage(::grpc::ServerContext* context, ::grpc::ServerReader< ::C_Stream::StreamRequest>* reader, ::C_Stream::StreamReply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace C_Stream

